services:
  web:
    container_name: shipping-web
    image: nginx:1.28-alpine3.21
    restart: always
    expose:
      - '8080' # customer portal
      - '8081' # admin portal
      - '8082' # API
      - '8084' # SDI dashboard
    volumes:
      - ./app/:/app/
      - ./docker/web/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app

  app:
    container_name: shipping-app
    hostname: ${APP_ENV}-shipping-app
    build:
      context: ./docker/app/
      args:
        APP_ENV: $APP_ENV
    restart: always
    init: true
    tty: true
    networks:
      - default
    env_file:
      - .env
    volumes:
      - ./app/:/app/
      - .env:/app/.env
    deploy:
      resources:
        limits:
          memory: 1G
