[program:php-fpm]
command=php-fpm --nodaemonize
autorestart=true
autostart=true
startsecs=5
startretries=1
stopwaitsecs=3
killasgroup=true
stopasgroup=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stdout_logfile_maxbytes=50MB    ; Rotate stdout log when it reaches 50MB
stdout_logfile_backups=10       ; Keep 10 backup copies of stdout log
stderr_logfile=/var/log/supervisor/%(program_name)s.error.log
stderr_logfile_maxbytes=50MB    ; Rotate stderr log when it reaches 50MB
stderr_logfile_backups=10       ; Keep 10 backup copies of stderr log

[program:cron]
command=cron -f
autostart=true
autorestart=true
killasgroup=true
stopasgroup=true
startsecs=5
startretries=1
stopwaitsecs=3
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stdout_logfile_maxbytes=50MB    ; Rotate stdout log when it reaches 50MB
stdout_logfile_backups=10       ; Keep 10 backup copies of stdout log
stderr_logfile=/var/log/supervisor/%(program_name)s.error.log
stderr_logfile_maxbytes=50MB    ; Rotate stderr log when it reaches 50MB
stderr_logfile_backups=10       ; Keep 10 backup copies of stderr log
